defaults:
  - _self_
  - agent: potil_vinn_offset
  - suite: robotgym
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: '/path/to/dir/FISH'

# replay buffer
replay_buffer_size: 150000
replay_buffer_num_workers: 2
nstep: 3
batch_size: 256
# misc
seed: 2
device: cuda
save_video: true
save_train_video: false
use_tb: true

# experiment
obs_type: 'pixels' # pixels, features
encoder_type: 'small' # small, resnet18, r3m, mvp (NOTE: r3m, mvp not supported for agent vinn)
experiment: exp_${suite.name}_${obs_type}_${task_name}_seed_${seed}

# expert dataset
num_demos: 1
expert_dataset: '${root_dir}/FISH/expert_demos/${suite.name}/${task_name}/expert_demos.pkl'

# Load weights
load_bc: false
# Weights
bc_weight: '${root_dir}/FISH/weights/${suite.name}_${obs_type}/${task_name}/bc.pt'

# Train with BC loss
bc_regularize: false
bc_weight_type: 'qfilter' # linear, qfilter

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
